apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apexvelocity.fullname" . }}
  labels:
    app: {{ include "apexvelocity.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "apexvelocity.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "apexvelocity.name" . }}
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      containers:
        - name: apexvelocity
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: AUTH_DISABLED
              value: "false"
          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12 }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
            capabilities:
              drop: {{- toYaml .Values.securityContext.capabilities.drop | nindent 16 }}


